version: '3'
services:
  db:
    image: mysql
    ports:
      - "3361:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: gitea
      MYSQL_PASSWORD: toor

  app:
    image: gitea/gitea
    ports:
      - "3000:3000"
    depends_on:
      - db
