version: '3'
services:
  db:
    image: mysql
    ports:
      - "3360:3306"
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: gogs
      MYSQL_PASSWORD: toor

  app:
    image: gogs/gogs
    ports:
      - "80:3000"
      - "2222:22"
    depends_on:
      - db
